import 'package:injectable/injectable.dart';
import 'package:pixabay/objectbox.g.dart';

final store = openStore(); // openStore is auto-generated by ObjectBox

@module
abstract class RegisterModule {
  @preResolve
  Future<Store> get store => openStore();
}
